name: Stock Scanner
on:
  schedule:
    - cron: '30 14 * * 1-5' # ירוץ ב-16:30 שעון ישראל בימי חול
  workflow_dispatch: # מאפשר לך להריץ ידנית לבדיקה
jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run logic
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
